### PR TITLE
set visibility of function text

### PR DESCRIPTION
**Pull request by DQNEO**
Thank you for a great tool.

I hope this fix helps it.

### CODE REVIEW

**Comment by DQNEO** [comment]
any problem?

**Comment by DQNEO** [comment]
@erusev May I hear your opinion about this?

**Comment by hkdobrev** [comment]
@DQNEO The accessor level of the methods in PHP is public by default. It depends on code style preference whether to explicitly state it or not.

**Comment by DQNEO** [comment]
Thank you for the feedback.

It may be a preference, but I think PSR is a de-facto standard.

http://www.php-fig.org/psr/psr-2/#1-overview

> Visibility MUST be declared on all properties and methods; 

If you don't like this PR, please close it. I don't mind at all.

**Comment by erusev** [comment]
i need to think about it a bit, but i'll probably convert all of the code to PSR eventually

**Comment by hkdobrev** [comment]
> i'll probably convert all of the code to PSR eventually

:+1: :clap:

**Comment by DQNEO** [comment]
:+1: 
I hope so.
I close this because one visibility change is not so useful.
Thank you for the response.

**Pull request closed without merging**
