### PR TITLE
Add "id" attribute to headings

### PR DESCRIPTION
**Pull request by henriquemoody**
This is more or less how GitHub Flavored Markdown works.

See an example: https://github.com/henriquemoody/parsedown/blob/titles/test/data/atx_heading.md

### CODE REVIEW

**Comment by henriquemoody** [comment]
Looks like the problem is on Travis, not in my feature.

Seems PHP 5.2 is no longer available.

**Comment by cebe** [comment]
> Seems PHP 5.2 is no longer available.

Yep, right: http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#PHP-VM

**Comment by GrahamCampbell** [comment]
Yeh. They had to remove it because it was no-longer building on their system.

**Comment by henriquemoody** [comment]
It's green now.

**Comment by erusev** [comment]
Thanks. I'll have a look at this next weekend.

**Comment by hkdobrev** [comment]
:+

**Comment by naNuke** [comment]
Why not use ATX function instead of adding buch of code into text()?

**Comment by henriquemoody** [comment]
@naNuke, I'm sorry but I don't know about ATX function. Can you elaborate?

**Comment by erusev** [comment]
> This is more or less how GitHub Flavored Markdown works.

Is it described in [the specification](https://help.github.com/articles/github-flavored-markdown/)?

**Comment by naNuke** [comment]
@henriquemoody line 468, sorry it was called atx in previous versions, now it's blockHeader()

**Comment by henriquemoody** [comment]
@erusev, no it's not in the spec but If you take a look on all processed Markdown files rendered by GitHub you will he something like that right after `<hN>` tags:

```html
<a name="this-is-an-anchor" class="anchor" href="#this-is-an-anchor">
    <span class="octicon octicon-link"></span>
</a>
```

I don't think put these tags on processed Markdown files is a good idea because it's based on the GitHub's CSS, but with the ids we still have the reference and we can link the titles. It's useful when you want to write a table of contents or just create an link to the same document.

**Comment by hkdobrev** [comment]
@erusev I don't think this is described in the spec. This is just how GitHub.com works. But it is really useful. Perhaps an extension? And then a community-driven wiki with a list of useful extensions?

**Comment by henriquemoody** [comment]
I think better I close this.

GitHub Flavored Markdown only does it on pages and wiki, but it's not a standard (you can see that on comments and issue descriptions), besides, this parser may/must be used to render lots of files, if two different files have the same title (header) the `id` will not be generated correctly.

**Comment by henriquemoody** [comment]
PS.: @erusev, I will keep my fork for a couple days, if you think this feature worth I will update it to reset the id counter every time something is rendered.

**Comment by erusev** [comment]
@henriquemoody 

Thanks for elaborating on this. Since this is not part of the GFM spec, I'd have to agree with @hkdobrev and suggest that it would make more sense as an extension.

**Comment by jmwright** [comment]
Has anyone created this extension, even if it hasn't been accepted into ParsedownExtra? I understand there are issues with it (same title and such), but I have a use case where I can control that if needed. If the extension doesn't exist I'll create it myself.

**Comment by kminchev** [comment]
This being a feature for Extra repo was my first thought about this. I even recall this being discussed before.

**Comment by jmwright** [comment]
Looks like it was discussed in issue #306 . Is there a reason that issue wasn't closed?

**Comment by henriquemoody** [comment]
@jmwright, see https://github.com/erusev/parsedown/pull/285#issuecomment-73551128

**Comment by sbrl** [comment]
Could this be added instead as an option that's disabled by default?

**Comment by innaj** [comment]
I think a lot of people will need inline document navigation: What about optionally add an id-tag to the headers. Header "My Header " => creates a  "my-header" id inside the header tag.

**Comment by decadence** [comment]
You can also create subclass without touching vendor files.
Laravel example.

```php
namespace App;

use Illuminate\Support\Str;

class HeadersParsedown extends \Parsedown
{
    protected function element(array $Element)
    {
        $headers = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'];

        $tag = $Element['name'];
        
        if (in_array($tag, $headers)) {
            $Element['attributes']['id'] = Str::slug($Element['text']);
        }

        return parent::element($Element);
    }
}
```

**Pull request closed without merging**
