### PR TITLE
Parsedown library shouldn't be executable

### PR DESCRIPTION
**Pull request by donatj**
I was doing a little security inventory and found Parsedown.php to be executable. 

As it's not shell executable, it should not be.

### CODE REVIEW

**Comment by erusev** [comment]
@hkdobrev could u share ur opinion on this

**Comment by hkdobrev** [comment]
:+1: It should not be executable. It doesn't have a shebang and it's not structured to be executed directly. `php Parsedown.php` could make sense, but it would work with 0644 as well. https://github.com/erusev/parsedown/pull/275 purpose is to provide an executable CLI tool.

**Comment by cebe** [comment]
:+1:

**Comment by erusev** [comment]
thanks @donatj for the PR and thanks @hkdobrev and @cebe for the expressed opinions

**Pull request merged**
