### PR TITLE
Update composer.json requirements

### LINKED ISSUE #374: Parse error
Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in my/path on line 1492

Link 1492: $instance = new static();

### PR DESCRIPTION
**Pull request by PhrozenByte**
Fixes #374

### CODE REVIEW

**Comment by hkdobrev** [comment]
:+1:

**Comment by erusev** [comment]
why does this fix #374

**Comment by PhrozenByte** [comment]
parsedown requries PHP 5.3+ (as stated in the `README.md`), this simply prevents (composer) installations with older PHP versions.

**Comment by hkdobrev** [comment]
BTW `composer` won't run on < PHP 5.3.3 anyway, but this change shows the minimum version on packagist as well so you know if you can use it in your environment.

**Comment by cebe** [comment]
composer needs php 5.3.3 or higher so there is not really a point in adding it.

**Comment by cebe** [comment]
@hkdobrev ha, same thought in the same second :)

**Comment by hkdobrev** [comment]
@cebe If it's missing, one could not assume if it would work everywhere where Composer works or if it was just omitted. Explicit it better than implicit.

**Comment by cebe** [comment]
fine with me. But we had the discussion already here: https://github.com/erusev/parsedown/pull/38

**Comment by hkdobrev** [comment]
I thought of #38 as well, but it's a bit different with PHP 5.2. However in both cases, I'd always prefer to state the requirement than leave it to the user to test and figure it out.

**Comment by PhrozenByte** [comment]
`composer.json` isn't necessarily limited to the `composer` cli, it can also be interpreted by other tools and services as well, like packagist. If there is a explicit requirement, specify it explicitly. This is common sense in like every package/dependency manager (e.g. `dpkg` and `rpm`). Never rely on that one of your dependencies (`composer` in this case) provides one of your direct dependencies (PHP 5.3+) implicitly, otherwise the dependency is completely out of your control.

**Comment by erusev** [comment]
> composer.json isn't necessarily limited to the composer cli, it can also be interpreted by other tools and services as well

that's a good point

**Comment by PhrozenByte** [comment]
Thank you @erusev :+1:

**Pull request merged**
