### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by erusev** [comment]
Sorry for taking me so long to respond.
Could you please explain the change? 
Thanks!

**Comment by GrahamCampbell** [comment]
It adds PHP 7.4 to the test suite, and pins the dists to the highest available for each PHP version, so next time Travis changes the default dist, stuff won't break again.

**Comment by erusev** [comment]
Sounds good.
Is setting dists a common practice?
Are there disadvantages?
Thanks!

**Comment by GrahamCampbell** [comment]
Yes, it's pretty common. Only advantages. You were setting the dist in the old config too, but that didn't didn't give you PHP 7.4. The only difference is now I am setting it for each version separately.

**Comment by erusev** [comment]
Great! Thanks!

**Pull request merged**
