### PR TITLE
Merge `1.8.x-beta` into `master`

### PR DESCRIPTION
**Pull request by xPaw**
The changes are minimal, master already had all the code changes from 1.8 branch, so this simply adds github actions and bumps up the php version.

@erusev mind taking a look so that there's less confusion about master and the 1.8 branch?

### CODE REVIEW

**Comment by erusev** [comment]
@xabbuh do you have any thoughts on this?

**Comment by xabbuh** [comment]
@erusev sounds reasonable to me

**Comment by erusev** [comment]
If we merge `1.8.x-beta` into `master`, can we then remove the `1.8.x-beta` branch? I find the branch situation a bit confusing.

**Comment by xPaw** [comment]
I believe it can be removed, yes.

**Comment by erusev** [comment]
> If we merge `1.8.x-beta` into `master`, can we then remove the `1.8.x-beta` branch? I find the branch situation a bit confusing.

@xabbuh do you have any thoughts on this?

**Comment by aragon999** [comment]
One thing, which is changed by this merge in addition to the changes which are in the 1.8.x branch, is that the tests are not compatible with php 7.1 (phpunit version 7.5).

But in my opinion this is fine, as this version is already eol for some time now (December 2019): https://www.php.net/eol.php

Maybe this php version should be dropped as well for the 1.8.0 release.

**Comment by xPaw** [comment]
PHPUnit 7 specifies PHP 7.1 - PHP 7.3 support, is that not the case?

The github action does have 7.1 in the test matrix, but it didn't run on this PR, so I'm not sure if it actually works.

**Comment by aragon999** [comment]
@xPaw ah yes, sorry for the confusion. I was thinking about it the other way around, i.e. see the following commment:
https://github.com/sebastianbergmann/phpunit/blob/7.5.20/src/Framework/TestCase.php#L407

But if you add the `void` declaration in the child class, it is fine: https://3v4l.org/tNYS3#v7.1.33

**Comment by xabbuh** [comment]
This looks reasonable to me. 👍

**Comment by erusev** [comment]
Should we also release `1.8.0` and make it latest? @aidantwoods @xabbuh  @xPaw

**Comment by xPaw** [comment]
I've been running that code in production for a while.

**Comment by erusev** [comment]
What should the release notes for `1.8.0` say?

**Comment by erusev** [comment]
@aidantwoods Would love to get your thoughts on this.

**Comment by erusev** [comment]
Looks like initially @aidantwoods wanted to release this as 1.8:

> On making this a minor release, I think it is certainly "fair game" due to not breaking the public API. -- https://github.com/erusev/parsedown/issues/601#issuecomment-387080763

But then he decided against it:

> I ended up deciding not to release 1.8.x as a minor upgrade due to quite a few internal changes that might break extensions. -- https://github.com/erusev/parsedown/issues/714#issuecomment-487721882

I'm open to releasing it as `2.0`, but the fact that @aidantwoods never released it as a stable release makes me wonder if it's good enough.

**Comment by joeworkman** [comment]
If you want to play it safe, release it as 2.0...

**Comment by xabbuh** [comment]
@Evgeny1973  with which version of this package do you get it?

**Comment by Evgeny1973** [comment]
@xabbuh Parsedown 1.7.4 and Symfony 7.1.

**Comment by Evgeny1973** [comment]
Sorry, as I see fixes of these depressions to the master branch have already been made. Looking forward to the release!

**Comment by dregad** [comment]
@xabbuh would it be possible to tag 1.7.5 with this fix ? see #889

**Pull request merged**
