### PR TITLE
Fix CommonMark test

### PR DESCRIPTION
**Pull request by PhrozenByte**
I was wondering what CommonMark examples are still violated by Parsedown, but the current test is broken (its regex matching the CommonMark examples doesn't work correctly). That is why I've developed a working one.

Parsedown currently passes 287 of 616 examples (i.e. 329 failures). Here's a complete `phpunit` run: http://pastebin.com/uLaJpBWf

```
FFF.FFFFF........FF.....F.F..F...F....FF....FF..F....FFF.F..FFF  63 / 616 ( 10%)
....FFFF....F..FFF.FFFFFFFFFFF.FFF.FFFFFFFFFFFFFF.F.FFFFFFFFF.. 126 / 616 ( 20%)
FF.FFFF...FF...F.FFFFFF.F.F.FF.FFFF.F.F.F.FF..FFF.FF......FF... 189 / 616 ( 30%)
.F..FFFFF...F...F..F..FFFF.F.....FFFFFF.FFFFF.F.FFFFFFF.FFFFF.. 252 / 616 ( 40%)
.FFFF.FFFF.F.FF.FFFFFFFFFFF.FF.F.FFF.F.FFFFFFFFFFF.FFFFF.F...FF 315 / 616 ( 51%)
..FFF..FF..FFF...FFF.F...FFFF.F.F..F..FF..FFFFFFF.FF....FF.FFF. 378 / 616 ( 61%)
...FFF.....FF.....FFF...............F..FF.......F..FF......F... 441 / 616 ( 71%)
FFFFFFFFFFFF..FF..FFF.FFFF.FFFFF.FF....F..FFFF..FFF..F..FFF.FFF 504 / 616 ( 81%)
.FFFFF.FFF.......F...F...F.....FFFFF.FF....F.F.FF.......FF.F.F. 567 / 616 ( 92%)
.FF.FF....FF.F..FF.....FFF..F.F..F.F.....F.......

FAILURES!
Tests: 616, Assertions: 616, Failures: 329.
```

One of the main reasons for that many failures is that Parsedown omits whitespaces where whitespaces shouldn't be omitted according to the CommonMark specs. However, many of these whitespaces don't matter when the page is viewed by a browser. That's the reason why I've created the `test/CommonMarkTestWeak.php`: This test cleans up the HTML markup before comparison, so examples which would normally fail due to actually invisible differences (e.g. superfluous whitespaces), don't fail. However, cleanup relies on block element detection. The detection doesn't work correctly when a element's `display` CSS property is manipulated. According to that this test should be only a interim solution on Parsedown's way to full CommonMark compatibility.

Parsedown currently passes 338 of 616 examples (i.e. 278 failures) when less aggressively compared. Here's a complete phpunit run: http://pastebin.com/CRNbXSdq

```
FFF.F.F...........F.....F.F..F...F.....F....FF..F.....FF....FFF  63 / 616 ( 10%)
....F.FF........FF..........FF.FF..FFF...F.F...FF...FFFFFFFFF.. 126 / 616 ( 20%)
FF.FFFF...FF...F.FFFF.F.F.F..F.FFFF.F.F.F.FF..F.F.FF........... 189 / 616 ( 30%)
....FFFFF...F...F..F..F..F.F......FFFFF.FF.FF.F.FFF...F.FFF.F.. 252 / 616 ( 40%)
.FFFF.FFFF.F.FF.FFFFFFF.F.F....F.FFF.F...FFFFFFFFF.FFFFF......F 315 / 616 ( 51%)
..FFF..FF..FFF...FFF.F...FFFF.F.F..F..FF..FFFFFFF.FF....FF.FFF. 378 / 616 ( 61%)
...FFF.....FF.....FFF...............F..FF.......F..FF......F... 441 / 616 ( 71%)
FFFFFFFFFFFF..FF..FFF.FFFF.FFFFF.FF....F..FFFF..FFF..F..FFF.FFF 504 / 616 ( 81%)
.FFFFF.FFF.......F...F...F.....FFFFF.FF....F.F.FF.......FF.F.F. 567 / 616 ( 92%)
.FF.FF....FF.F..FF.....FFF..F.F..F.F.............

FAILURES!
Tests: 616, Assertions: 616, Failures: 278.
```

Please note that fulfilling all CommonMark spec examples doesn't make Parsedown fully compatible to CommonMark. There are some more things to consider. However, making the examples work is a good starting point.

Please also note that Parsedown not only fails examples which represent "cases that are quite uncommon" (according to the `README.md`) - some of the failed tests are quite important (e.g. hard line breaks, #334).

### CODE REVIEW

**Comment by erusev** [comment]
> hard line breaks

Do you mean back slash line breaks?

**Comment by PhrozenByte** [comment]
Yes, exactly.
```
276) CommonMarkTestWeak::testExample with data set #597 ('Hard line breaks', 'foo\\
baz', '<p>foo<br />
baz</p>')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<p>foo<br />
+'<p>foo\
 baz</p>'
```

However, I have to be honest: I didn't read all failing examples, just a bunch of them. I was focusing on making the tests work :smile:

**Comment by erusev** [comment]
Thanks, I've been very busy preparing the next major release of @careteditor, but as soon as I have some time, I'll look into it.

**Comment by PhrozenByte** [comment]
Great, thanks @erusev :smiley:

I've now pushed commit 33a23fb to this PR what refactors Parsedown's PHPUnit bootstrap. The goal of this change is to make PHPUnit of [`erusev/parsedown-extra`](https://github.com/erusev/parsedown-extra) work again (see erusev/parsedown-extra#96 for details). I wasn't sure whether to open a new PR for this or to add it to this PR, especially because [this change](https://github.com/erusev/parsedown/pull/423/commits/33a23fbfb22902e6268b8459af2784803aec8848#diff-d8c2afb78142023e0fe9e41457558372L16) is necessary to make the original changes of this PR work with 33a23fb (kind of a dependency hell). If you want me to open another PR for 33a23fb just tell me. :smiley:

**Comment by erusev** [comment]
Thanks, hopefully, I'll have a chance to review it soon enough.

**Comment by PhrozenByte** [comment]
btw: It would seem useful to add the `CommonMarkTest.php` (or `CommonMarkTestWeak.php`) in a *non-breaking* way (i.e. `|| true`) to Travis, e.g. with
```yaml
script:
  - phpunit test/CommonMarkTest.php || true
```
This way it gets very easy to check whether a PR improves CommonMark compliance or not. Should I add this to the PR @erusev?

**Comment by erusev** [comment]
Sure, it'd take me some time to review the whole thing, though.

**Comment by PhrozenByte** [comment]
Sure, fixing the failing tests definitely is a quite big thing, however, IMHO it is useful to merge this before actually starting to improve CommonMark compliance.

**Comment by erusev** [comment]
Sure, hopefully, I'll have some time to look into it later this month.

**Comment by PhrozenByte** [comment]
Since there was some progress related to Parsedown's build process and Travis lately (#539), I've solved the merge conflicts and would like to express my hope to merge this @erusev.

The changes look bigger than they are, it's basically just a bugfix, but is nevertheless a huge improvement towards Parsedown's build and test process. Parsedown's `CommonMarkTest` is broken at the moment due to a regex not taking some special cases in the CommonMark spec file into account.

**Comment by erusev** [comment]
@PhrozenByte I think this would make more sense for Parsedown 2.0 which should be more CommonMark aware. Hopefully, I can release a 2.0 branch in a couple of months. For the current version, I'd like to focus the limited time I can dedicate to it on priority issues. I appreciate the work that you've put here and I hope that you won't be disappointed with my response.

**Pull request merged**
