### PR TITLE
Updated to PSR-1 & PSR-2

### PR DESCRIPTION
**Pull request by BenjaminHoegh**
Updated to follow the PSR-1, PSR-2 rules

### CODE REVIEW

**Comment by BenjaminHoegh** [comment]
lol, #TravisCI it works you monkeys

**Comment by aidantwoods** [comment]
I think we could incorporate some of these (e.g. adding the explicit `public` modifier to public functions), although I don't think most of these changes would work for right now:

Unfortunately a lot of these are breaking changes (e.g. changing the names of instance variables and constants) – this is why the Travis build is failing.

On camelCasing local variables: in Parsedown the existing convention is to use PascalCase for arrays that have some expected structure (e.g. line and element structures). This could perhaps be dropped in a new major release when transitioning to objects to place type safety constraints on these structures, but as of now this notation provides readability value and helps communicate the writers intent.

IMO while Parsedown is in a single file, liberal use of whitespace also helps readability by sectioning off relevant disjoint components or sections of a function (I'm not sure why it is being removed even between function definitions).

On brace placement for `if`s and loops, IMO putting the brace on the next line helps clarify sectioning better (Parsedown's `if` clauses along with the body of both `if` and loop constructs are typically non-trivial), and so I think the need for clearer sectioning is justified.

**Comment by BenjaminHoegh** [comment]
@aidantwoods what about namespace? should it be added?

**Comment by aidantwoods** [comment]
For the next major version, likely yes :) See https://github.com/erusev/parsedown/pull/617

**Pull request closed without merging**
